# This workflow will do a clean install of node dependencies, and run the linter
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [default]
  pull_request:
    branches: [default]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          # For commitlint; ideally this would only check out the feature branch's history, but
          # that's not currently an option.
          fetch-depth: ${{ github.event_name == 'push' }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run ci --if-present

  release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/default'
    runs-on: ubuntu-latest

    needs: [lint]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - name: Release
        run: npx semantic-release -b default
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
